export const dummyData = [
  {
    id: '1',
    name: '네헤브릭',
    category: '베팅',
    people: '50명',
    time: 60,
    description: '',
    location: '3',
    locationName: '미스바 성전(본관) - 2층 강당',
  },
  {
    id: '2',
    name: '벽돌을 지켜라',
    category: '추리/전략',
    people: '20명',
    time: 60,
    description: '',
    location: '2',
    locationName: '로뎀의 집 - 1층 소강당',
  },
  {
    id: '3',
    name: '경로를 재탐색합니다',
    category: '기억력',
    people: '10명',
    time: 40,
    description: '',
    location: '2',
    locationName: '로뎀의 집 - 1층 중강당',
  },
  {
    id: '4',
    name: '파수꾼의 계산법',
    category: '수학/전략',
    people: '30명',
    time: 40,
    description: '',
    location: '2',
    locationName: '로뎀의 집 - 203호',
  },
  {
    id: '5',
    name: '집 밖을 나왔더니 성벽이!',
    category: '방탈출',
    people: '10명',
    time: 40,
    description: '',
    location: '2',
    locationName: '로뎀의 집 - 308~10호',
  },
  {
    id: '6',
    name: '집 밖을 나왔더니 성벽이!',
    category: '방탈출',
    people: '10명',
    time: 40,
    description: '',
    location: '2',
    locationName: '로뎀의 집 - 305~7호',
  },
  {
    id: '7',
    name: '묵언열차',
    category: '센스',
    people: '20~30명',
    time: 30,
    description: '',
    location: '4',
    locationName: '야외',
  },
  {
    id: '8',
    name: '와 성경이 들린다',
    category: '기억력/지식',
    people: '10명',
    time: 30,
    description: '',
    location: '1',
    locationName: '벧엘의 집 - 211호',
  },
  {
    id: '9',
    name: '네헴의 4번 타자',
    category: '순발력/센스',
    people: '10명',
    time: 30,
    description: '',
    location: '1',
    locationName: '벧엘의 집 - 101호',
  },
  {
    id: '10',
    name: '네헴의 4번 타자',
    category: '순발력/센스',
    people: '10명',
    time: 30,
    description: '',
    location: '1',
    locationName: '벧엘의 집 - 102호',
  },
];
